### ISSUE TITLE
New languages should be added

### ISSUE THREAD

**Issue by m-aciek** [django/djangopeople#73]
Django People has [16 completed translations on Transifex](https://www.transifex.com/django/djangopeople/dashboard/), and only 7 of them are released publicly. How about adding them?

**Comment by timgraham** [comment]
@brutasse, do you have time to do that and document the process?

**Comment by m-aciek** [comment]
I've just finished [Polish translation](https://www.transifex.com/django/djangopeople/language/pl/). @brutasse, could you please add it either?

**Comment by brutasse** [comment]
@m-aciek polish translation added. Thanks!
