### ISSUE TITLE
Cannot login - is app hacked?

### ISSUE THREAD

**Issue by unixconky** [django/djangopeople#96]
After login:

![Screenshot_2019-07-12 Taghvim com 404](https://user-images.githubusercontent.com/25853438/61106399-54acf880-a47d-11e9-9904-0baf36c7a264.png)

**Comment by apollo13** [comment]
Hi, there is no indication that the app got hacked or anything but we have seeing this issue too. I wonder if some weird routing at AWS was happening :/ Either way, if you still have this issue remove the service worker for djangopeople.net and clear your cache.
